#!/usr/bin/env python3
"""
------------------------------------------------------------
Project : RTL to GDS of SPI Protocol
Author  : Agnibha Sarkar
Purpose : Automatically generate a PDNSim voltage source
          (.loc) file from a DEF file.

Usage:
    python3 generate_pdn_sources.py \
        spi_top_physical_signoff.def \
        vsrc.loc

Optional:
    python3 generate_pdn_sources.py \
        spi_top_physical_signoff.def \
        vsrc.loc \
        --spacing 2 \
        --voltage 1.8 \
        --layer met5
------------------------------------------------------------
"""

import argparse
import math
import re


# ------------------------------------------------------------
# Parse command-line arguments
# ------------------------------------------------------------
parser = argparse.ArgumentParser()

parser.add_argument(
    "def_file",
    help="Input DEF file"
)

parser.add_argument(
    "output_file",
    help="Output PDNSim voltage source file"
)

parser.add_argument(
    "--spacing",
    type=int,
    default=1,
    help="Place one voltage source every N routing tracks."
)

parser.add_argument(
    "--voltage",
    type=float,
    default=0.7,
    help="Supply voltage."
)

parser.add_argument(
    "--layer",
    default="M5",
    help="Routing layer to use."
)

args = parser.parse_args()


# ------------------------------------------------------------
# Read DEF
# ------------------------------------------------------------
with open(args.def_file) as f:
    def_text = f.read()


# ------------------------------------------------------------
# Parse DIEAREA
# ------------------------------------------------------------
die_match = re.search(
    r"DIEAREA\s*\(\s*(\d+)\s+(\d+)\s*\)\s*\(\s*(\d+)\s+(\d+)\s*\)",
    def_text,
)

if die_match is None:
    raise RuntimeError("Could not locate DIEAREA.")

lx = int(die_match.group(1))
ly = int(die_match.group(2))
ux = int(die_match.group(3))
uy = int(die_match.group(4))


# DEF units are nanometers for Sky130 (1000 DBU = 1 µm)
DBU = 1000.0

die_width = (ux - lx) / DBU
die_height = (uy - ly) / DBU


# ------------------------------------------------------------
# Parse TRACKS
# ------------------------------------------------------------
track_pattern = (
    r"TRACKS\s+([XY])\s+(\d+)\s+DO\s+(\d+)\s+STEP\s+(\d+)\s+LAYER\s+"
    + re.escape(args.layer)
)

tracks = re.findall(track_pattern, def_text)

if len(tracks) != 2:
    raise RuntimeError(
        f"Could not find X and Y TRACK definitions for {args.layer}."
    )


track_info = {}

for axis, origin, count, step in tracks:

    track_info[axis] = {
        "origin": int(origin) / DBU,
        "count": int(count),
        "step": int(step) / DBU,
    }


x_origin = track_info["X"]["origin"]
x_count = track_info["X"]["count"]
x_step = track_info["X"]["step"]

y_origin = track_info["Y"]["origin"]
y_count = track_info["Y"]["count"]
y_step = track_info["Y"]["step"]


# ------------------------------------------------------------
# Generate voltage source locations
# ------------------------------------------------------------
points = []

for ix in range(0, x_count, args.spacing):

    x = x_origin + ix * x_step

    for iy in range(0, y_count, args.spacing):

        y = y_origin + iy * y_step

        if x <= die_width and y <= die_height:

            points.append((x, y))


# ------------------------------------------------------------
# Write output file
# ------------------------------------------------------------
SOURCE_SIZE = 20.0

with open(args.output_file, "w") as f:

    #f.write("#---------------------------------------------\n")
    #f.write("# Auto-generated by generate_pdn_sources.py\n")
    #f.write("#\n")
    #f.write("# x(um)   y(um)   voltage(V)\n")
    #f.write("#---------------------------------------------\n\n")

    for x, y in points:

        f.write(
            f"{x:8.3f},{y:8.3f},{SOURCE_SIZE:8.3f},{args.voltage:.3f}\n"
        )


# ------------------------------------------------------------
# Summary
# ------------------------------------------------------------
print("\n========== PDNSim Voltage Source Generator ==========")

print(f"Input DEF      : {args.def_file}")
print(f"Output File    : {args.output_file}")

print()

print(f"Die Width      : {die_width:.3f} um")
print(f"Die Height     : {die_height:.3f} um")

print()

print(f"Layer          : {args.layer}")
print(f"Track Origin X : {x_origin:.3f} um")
print(f"Track Origin Y : {y_origin:.3f} um")
print(f"Track Pitch X  : {x_step:.3f} um")
print(f"Track Pitch Y  : {y_step:.3f} um")

print()

print(f"Spacing        : Every {args.spacing} track(s)")
print(f"Voltage        : {args.voltage:.3f} V")
print(f"Voltage Sources: {len(points)}")

print("=====================================================\n")